services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

    # passando variaveis de ambiente
    # environment:
    #   POSTGRES_PASSWORD: "local_password"
    # ports:
    #   - "5432:5432"
    # passando variaveis usando arquido do dotenv
    #  env_file:
    #   - ../.env
    # ports:
    #   - "5432:5432"
